import = [
  "/home/zetrext/.config/alacritty/tokyo.toml",
  "/home/zetrext/.config/alacritty/fonts-main.toml",
]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "none"
dynamic_title = true
# history = 10000
# multiplier = 3
opacity = 0.98
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 12
y = 12
