#!/usr/bin/env bash

set -e

if (! git rev-parse --git-common-dir >/dev/null); then
	echo "You are not in a git worktree"
	exit 1
fi

set +e

# Cd into the base worktree
git_worktree_base=$(git rev-parse --git-common-dir)
cd "$git_worktree_base"

# Let the user pick from the branches in origin
branch_names=$(find ./refs/remotes/origin -mindepth 1 -maxdepth 1 -type f)
selected=$(echo "$branch_names" | fzf --header="Select branch to checkout")

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)

echo "Adding worktree for origin branch $selected_name"
git worktree add "$selected_name"
git branch --set-upstream-to=origin/"$selected_name" "$selected_name"
